# Supabase Configuration
# Copy this file and rename to secrets.toml (remove .example)
# Add your actual Supabase credentials

SUPABASE_URL = "https://jlvkyasuvvgjdamhnwlb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsdmt5YXN1dnZnamRhbWhud2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzMyOTAsImV4cCI6MjA2ODMwOTI5MH0.CVhdtnlSphfZTJD1qibN_jQnpu6hog1E27f-RrLI8us"

# Note: Make sure the bucket "fidc-files" exists in your Supabase Storage
# and has the appropriate policies configured for public read access
